"""
P&L tracker with live rebate calculation.

Polymarket fee/rebate model for crypto markets:
  - Makers pay $0 in fees
  - Taker fee formula: shares × rate × price × (1 - price)
  - Maker rebate: 20% of taker fees collected in the market
  - Rebates distributed daily in USDC, proportional to maker volume
  - We ESTIMATE rebates in real-time based on our fill volume

Crypto fee params (from feeSchedule):
  rate = 0.072 (7.2%)
  rebateRate = 0.2 (20% of taker fees go to makers)
"""

import time
from dataclasses import dataclass, field
from src.monitoring.logger import get_logger

log = get_logger("pnl_tracker")


# Fee schedule constants from Polymarket API
CRYPTO_FEE_RATE = 0.072          # 7.2% base rate
CRYPTO_REBATE_SHARE = 0.20       # 20% of taker fees → maker rebates
MAKER_VOLUME_SHARE = 0.50        # Our assumed share of total maker volume
REWARDS_MIN_SIZE = 50            # Min order size for rewards eligibility
REWARDS_MAX_SPREAD = 0.045       # Max spread (4.5¢) for rewards eligibility


def compute_taker_fee(shares: float, price: float,
                      rate: float = CRYPTO_FEE_RATE) -> float:
    """
    Compute the taker fee for a trade.
    
    Fee = shares × rate × price × (1 - price)
    
    Bell-shaped: highest at price=0.50, zero at 0.00 or 1.00.
    """
    return shares * rate * price * (1.0 - price)


def estimate_maker_rebate(shares: float, price: float,
                          rate: float = CRYPTO_FEE_RATE,
                          rebate_share: float = CRYPTO_REBATE_SHARE,
                          volume_share: float = MAKER_VOLUME_SHARE) -> float:
    """
    Estimate our maker rebate for a fill.
    
    Each of our maker fills was matched against a taker.
    The taker paid: shares × rate × price × (1 - price)
    We receive: rebate_share × taker_fee × volume_share
    
    Args:
        shares: Number of shares filled.
        price: Fill price.
        rate: Fee rate from feeSchedule.
        rebate_share: Fraction of taker fees distributed to makers.
        volume_share: Our estimated share of total maker volume.
    
    Returns:
        Estimated rebate in USDC.
    """
    taker_fee = compute_taker_fee(shares, price, rate)
    return taker_fee * rebate_share * volume_share


@dataclass
class FillRecord:
    """Single fill event with rebate calculation."""
    timestamp: float
    side: str           # "yes" (Up) or "no" (Down)
    size: float         # Number of shares
    price: float        # Fill price
    asset: str
    market_id: str
    taker_fee: float    # Fee the taker paid
    est_rebate: float   # Our estimated rebate from this fill
    notional: float     # size × price


@dataclass 
class PnLSnapshot:
    timestamp: float = 0.0
    spread_income: float = 0.0       # From matched pairs (Up+Down < $1)
    settlement_pnl: float = 0.0      # From resolved markets
    outcome_pnl: float = 0.0         # From unmatched-token actual outcomes
    unrealized_pnl: float = 0.0      # MTM on open positions
    total_fees: float = 0.0          # Gas + platform fees (0 for makers)
    est_rebates: float = 0.0         # Estimated maker rebates
    net_trading_pnl: float = 0.0     # matched-pair/merge P&L - fees
    net_pnl_with_rebates: float = 0.0  # matched-pair/merge P&L + rebates (legacy)
    economic_pnl: float = 0.0        # matched-pair/merge + outcome + rebates
    markets_traded: int = 0
    markets_settled: int = 0
    total_fills: int = 0
    total_volume: float = 0.0        # Total notional volume
    total_shares: float = 0.0        # Total shares traded
    avg_rebate_per_fill: float = 0.0
    rebate_rate_bps: float = 0.0     # Effective rebate rate in bps
    starting_capital: float = 0.0
    current_capital: float = 0.0


class PnLTracker:
    def __init__(self, fee_rate: float = CRYPTO_FEE_RATE,
                 rebate_share: float = CRYPTO_REBATE_SHARE,
                 volume_share: float = MAKER_VOLUME_SHARE):
        self.fee_rate = fee_rate
        self.rebate_share = rebate_share
        self.volume_share = volume_share

        # Core P&L
        self.settlement_pnl = 0.0
        self.outcome_pnl = 0.0
        self.total_fees = 0.0          # Maker fees = $0
        self.spread_income = 0.0

        # Rebate tracking
        self.est_rebates = 0.0         # Running total estimated rebates
        self.total_taker_fees = 0.0    # Total taker fees generated by our fills

        # Counters
        self.markets_settled = 0
        self.markets_traded = 0
        self.total_fills = 0
        self.total_volume = 0.0        # Notional volume
        self.total_shares = 0.0        # Raw share count

        # Per-asset rebates
        self._asset_rebates: dict[str, float] = {}
        self._asset_fills: dict[str, int] = {}
        self._asset_volume: dict[str, float] = {}
        self._settled_markets: set[str] = set()

        self._fills: list[FillRecord] = []
        self._session_start = time.time()
        
        # Capital tracking
        self.starting_capital = 500.0  # Will be set in main
        self.current_capital = 500.0

    def record_capital_recovery(self, amount: float):
        self.current_capital += amount

    def record_fill(self, size: float, price: float,
                    side: str = "", asset: str = "",
                    market_id: str = ""):
        """
        Record a maker fill and compute estimated rebate.
        
        Args:
            size: Number of shares filled.
            price: Fill price.
            side: "yes" (Up) or "no" (Down).
            asset: Asset name (BTC, ETH, etc.).
            market_id: Market condition ID.
        """
        self.total_fills += 1
        notional = size * price
        self.total_volume += notional
        self.total_shares += size
        self.current_capital -= notional

        # Compute rebate
        taker_fee = compute_taker_fee(size, price, self.fee_rate)
        rebate = estimate_maker_rebate(size, price, self.fee_rate,
                                       self.rebate_share, self.volume_share)

        self.total_taker_fees += taker_fee
        self.est_rebates += rebate

        # Per-asset tracking
        if asset:
            self._asset_rebates[asset] = self._asset_rebates.get(asset, 0) + rebate
            self._asset_fills[asset] = self._asset_fills.get(asset, 0) + 1
            self._asset_volume[asset] = self._asset_volume.get(asset, 0) + notional

        # Record fill
        fill = FillRecord(
            timestamp=time.time(),
            side=side,
            size=size,
            price=price,
            asset=asset,
            market_id=market_id[:8] if market_id else "",
            taker_fee=taker_fee,
            est_rebate=rebate,
            notional=notional,
        )
        self._fills.append(fill)

        log.info("fill_rebate",
                 asset=asset,
                 side=side,
                 size=size,
                 price=price,
                 taker_fee=round(taker_fee, 6),
                 est_rebate=round(rebate, 6),
                 total_rebates=round(self.est_rebates, 4))

    def record_spread_income(self, up_price: float, down_price: float,
                              matched_pairs: float):
        """Record spread income from matched Up+Down pairs."""
        if matched_pairs > 0:
            edge = 1.0 - (up_price + down_price)
            income = edge * matched_pairs
            self.spread_income += income

    def record_pair_merge(self, pnl: float, market_id: str = ""):
        """Record matched-pair/merge P&L without counting the market settled.

        A mid-market merge only converts matched YES+NO inventory back to
        collateral. The market is still active, so target-window accounting must
        not advance here.
        """
        self.settlement_pnl += pnl
        log.info("pnl_pair_merge",
                 market=market_id[:8] if market_id else "",
                 pnl=round(pnl, 4),
                 total=round(self.settlement_pnl, 4))

    def record_settlement(self, pnl: float, market_id: str = ""):
        self.settlement_pnl += pnl
        if market_id:
            if market_id not in self._settled_markets:
                self._settled_markets.add(market_id)
                self.markets_settled += 1
        else:
            self.markets_settled += 1
        log.info("pnl_settlement",
                 market=market_id[:8] if market_id else "",
                 pnl=round(pnl, 4),
                 total=round(self.settlement_pnl, 4))

    def _mark_market_settled(self, market_id: str = ""):
        """Count a settled market once without changing any P&L bucket."""
        if market_id:
            if market_id not in self._settled_markets:
                self._settled_markets.add(market_id)
                self.markets_settled += 1
        else:
            self.markets_settled += 1

    def record_outcome_resolution(self, pnl: float, market_id: str = ""):
        """Record P&L from unmatched inventory after actual market outcome.

        Outcome P&L is intentionally separate from matched-pair/merge P&L.
        Older code routed this through record_settlement(), which made reports
        ambiguous and risked double-counting in summary displays.
        """
        self.outcome_pnl += pnl
        self._mark_market_settled(market_id)
        log.info("outcome_pnl_recorded",
                 market=market_id[:8] if market_id else "",
                 pnl=round(pnl, 4),
                 total_outcome_pnl=round(self.outcome_pnl, 4))

    def record_fee(self, amount: float):
        """Record platform fee (should be $0 for makers)."""
        self.total_fees += amount

    def snapshot(self, unrealized: float = 0.0) -> PnLSnapshot:
        trading_pnl = self.settlement_pnl + self.spread_income - self.total_fees
        net_with_rebates = trading_pnl + unrealized + self.est_rebates
        economic_pnl = net_with_rebates + self.outcome_pnl
        avg_rebate = self.est_rebates / max(1, self.total_fills)
        rebate_bps = (self.est_rebates / max(0.01, self.total_volume)) * 10000

        snap = PnLSnapshot(
            timestamp=time.time(),
            spread_income=self.spread_income,
            settlement_pnl=self.settlement_pnl,
            outcome_pnl=self.outcome_pnl,
            unrealized_pnl=unrealized,
            total_fees=self.total_fees,
            est_rebates=self.est_rebates,
            net_trading_pnl=trading_pnl + unrealized,
            net_pnl_with_rebates=net_with_rebates,
            economic_pnl=economic_pnl,
            markets_traded=self.markets_traded,
            markets_settled=self.markets_settled,
            total_fills=self.total_fills,
            total_volume=self.total_volume,
            total_shares=self.total_shares,
            avg_rebate_per_fill=avg_rebate,
            rebate_rate_bps=rebate_bps,
            starting_capital=self.starting_capital,
            current_capital=self.current_capital,
        )
        return snap

    @property
    def net_pnl(self) -> float:
        """Legacy net P&L: matched-pair/merge P&L plus estimated rebates."""
        return self.settlement_pnl + self.spread_income - self.total_fees + self.est_rebates

    @property
    def economic_pnl(self) -> float:
        """Total economic P&L: matched-pair/merge + outcome + rebates."""
        return self.net_pnl + self.outcome_pnl

    @property
    def net_trading_pnl(self) -> float:
        """Net P&L from trading only (no rebates)."""
        return self.settlement_pnl + self.spread_income - self.total_fees

    @property
    def session_duration_hours(self) -> float:
        return (time.time() - self._session_start) / 3600

    def rebates_per_hour(self) -> float:
        hours = self.session_duration_hours
        if hours < 0.001:
            return 0.0
        return self.est_rebates / hours

    def asset_summary(self) -> dict:
        """Per-asset rebate summary."""
        summary = {}
        for asset in self._asset_rebates:
            summary[asset] = {
                "fills": self._asset_fills.get(asset, 0),
                "volume": round(self._asset_volume.get(asset, 0), 2),
                "rebates": round(self._asset_rebates.get(asset, 0), 6),
            }
        return summary
